import { Component, OnDestroy, OnInit, computed, inject, signal } from '@angular/core';

import type {
  LocalEmbeddingModelDownloadProgress,
  LocalEmbeddingModelStatus,
  UninstallLocalEmbeddingModelPayload,
} from '../../../../../../shared/models/vector.model';
import { ElectronService } from '../../../../core/services/electron.service';
import { ConfirmModalService } from '../../../../shared/components/confirm-modal/confirm-modal.service';

import { AiProviderIconComponent } from '../ai-configuration-settings/ai-provider-icon.component';

type VectorCloudProviderId = 'openai' | 'voyage';

interface VectorCloudProvider {
  id: VectorCloudProviderId;
  name: string;
  description: string;
  keyPlaceholder: string;
}

type LocalModelOperation = 'download' | 'uninstall';

@Component({
  selector: 'app-vector-configuration-settings',
  imports: [AiProviderIconComponent],
  templateUrl: './vector-configuration-settings.component.html',
  styleUrl: '../ai-configuration-settings/ai-configuration-settings.component.scss',
})
export class VectorConfigurationSettingsComponent implements OnInit, OnDestroy {
  private readonly electronService = inject(ElectronService);
  private readonly confirmService = inject(ConfirmModalService);
  private removeDownloadProgressListener: () => void = () => {};

  readonly providers: readonly VectorCloudProvider[] = [
    {
      id: 'openai',
      name: 'OpenAI',
      description: 'Create manuscript embeddings with OpenAI models.',
      keyPlaceholder: 'sk-...',
    },
    {
      id: 'voyage',
      name: 'Voyage AI',
      description: 'Create manuscript embeddings with Voyage models.',
      keyPlaceholder: 'Enter your Voyage AI API key',
    },
  ];

  readonly selectedProviderId = signal<VectorCloudProviderId | null>(null);
  readonly apiKeyVisible = signal(false);
  readonly apiKeyDrafts = signal<Record<VectorCloudProviderId, string>>({
    openai: '',
    voyage: '',
  });
  readonly localModelStatus = signal<LocalEmbeddingModelStatus | null>(null);
  readonly localModelStatusLoading = signal(true);
  readonly localModelOperation = signal<LocalModelOperation | null>(null);
  readonly localModelProgress = signal<LocalEmbeddingModelDownloadProgress | null>(null);
  readonly localModelError = signal<string | null>(null);

  readonly selectedProvider = computed(() => {
    const providerId = this.selectedProviderId();
    return this.providers.find((provider) => provider.id === providerId) ?? null;
  });

  ngOnInit(): void {
    this.removeDownloadProgressListener = this.electronService.on(
      'vectors:local-model:download-progress',
      (progress: LocalEmbeddingModelDownloadProgress) => {
        if (this.localModelOperation() === 'download') this.localModelProgress.set(progress);
      },
    );
    void this.loadLocalModelStatus();
  }

  ngOnDestroy(): void {
    this.removeDownloadProgressListener();
  }

  async loadLocalModelStatus(): Promise<void> {
    this.localModelStatusLoading.set(true);
    this.localModelError.set(null);
    try {
      const status = await this.electronService.invoke('vectors:local-model:get-status');
      this.localModelStatus.set(status as LocalEmbeddingModelStatus);
    } catch (error) {
      this.localModelError.set(this.errorMessage(error));
    } finally {
      this.localModelStatusLoading.set(false);
    }
  }

  async downloadLocalModel(): Promise<void> {
    if (this.localModelOperation()) return;

    this.localModelOperation.set('download');
    this.localModelProgress.set(null);
    this.localModelError.set(null);
    try {
      const status = await this.electronService.invoke('vectors:local-model:download');
      this.localModelStatus.set(status as LocalEmbeddingModelStatus);
    } catch (error) {
      const downloadError = this.errorMessage(error);
      try {
        const status = await this.electronService.invoke('vectors:local-model:get-status');
        this.localModelStatus.set(status as LocalEmbeddingModelStatus);
        this.localModelError.set(downloadError);
      } catch (statusError) {
        this.localModelError.set(
          `${downloadError} Status refresh failed: ${this.errorMessage(statusError)}`,
        );
      }
    } finally {
      this.localModelOperation.set(null);
      this.localModelProgress.set(null);
    }
  }

  requestLocalModelUninstall(): void {
    if (this.localModelOperation()) return;

    const status = this.localModelStatus();
    const action = status?.installed ? 'Uninstall' : 'Remove downloaded files for';
    this.confirmService.open(
      `${action} local model?`,
      `${status?.modelName ?? 'The local embedding model'} will be removed from this device. You can download it again later.`,
      (clearVectors) => {
        void this.uninstallLocalModel(clearVectors);
      },
      undefined,
      {
        confirmLabel: status?.installed ? 'Uninstall' : 'Remove files',
        checkboxLabel: 'Also delete vectors generated by this model.',
      },
    );
  }

  formatBytes(bytes: number): string {
    if (bytes === 0) return '0 B';

    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    const unitIndex = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
    const value = bytes / 1024 ** unitIndex;
    return `${new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(value)} ${units[unitIndex]}`;
  }

  downloadPercentage(): number | null {
    const progress = this.localModelProgress();
    if (!progress) return null;
    if (typeof progress.progress === 'number') return this.clampPercentage(progress.progress);
    if (
      typeof progress.loaded === 'number' &&
      typeof progress.total === 'number' &&
      progress.total > 0
    ) {
      return this.clampPercentage((progress.loaded / progress.total) * 100);
    }
    return null;
  }

  private async uninstallLocalModel(clearVectors: boolean): Promise<void> {
    if (this.localModelOperation()) return;

    this.localModelOperation.set('uninstall');
    this.localModelError.set(null);
    try {
      const payload: UninstallLocalEmbeddingModelPayload = { clearVectors };
      const status = await this.electronService.invoke('vectors:local-model:uninstall', payload);
      this.localModelStatus.set(status as LocalEmbeddingModelStatus);
    } catch (error) {
      this.localModelError.set(this.errorMessage(error));
    } finally {
      this.localModelOperation.set(null);
    }
  }

  private clampPercentage(value: number): number {
    return Math.round(Math.min(100, Math.max(0, value)));
  }

  private errorMessage(error: unknown): string {
    return error instanceof Error ? error.message : String(error);
  }

  selectProvider(providerId: VectorCloudProviderId): void {
    this.selectedProviderId.set(providerId);
    this.apiKeyVisible.set(false);
  }

  updateApiKey(providerId: VectorCloudProviderId, event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.apiKeyDrafts.update((drafts) => ({ ...drafts, [providerId]: value }));
  }

  toggleApiKeyVisibility(): void {
    this.apiKeyVisible.update((visible) => !visible);
  }

  apiKeyInputType(): 'text' | 'password' {
    return this.apiKeyVisible() ? 'text' : 'password';
  }

  /** Persistence will be connected when the vector configuration backend is implemented. */
  saveApiKeyOnBlur(_providerId: VectorCloudProviderId): void {}

  /** Connection testing will be connected when the vector configuration backend is implemented. */
  testConnection(_providerId: VectorCloudProviderId): void {}
}
