import { Component, OnInit, computed, inject, signal } from '@angular/core';

import type {
  LocalEmbeddingModelName,
  LocalEmbeddingModelStatus,
  LocalEmbeddingModelTier,
} from '../../../../../../shared/models/vector.model';
import { ConfirmModalService } from '../../../../shared/components/confirm-modal/confirm-modal.service';
import {
  LocalEmbeddingModelStateService,
  type LocalModelOperationType,
} from '../../services/local-embedding-model-state.service';

import { AiProviderIconComponent } from '../ai-configuration-settings/ai-provider-icon.component';

type VectorCloudProviderId = 'openai' | 'voyage';

interface VectorCloudProvider {
  id: VectorCloudProviderId;
  name: string;
  description: string;
  keyPlaceholder: string;
}

@Component({
  selector: 'app-vector-configuration-settings',
  imports: [AiProviderIconComponent],
  templateUrl: './vector-configuration-settings.component.html',
  styleUrl: '../ai-configuration-settings/ai-configuration-settings.component.scss',
})
export class VectorConfigurationSettingsComponent implements OnInit {
  private readonly localModelState = inject(LocalEmbeddingModelStateService);
  private readonly confirmService = inject(ConfirmModalService);

  readonly providers: readonly VectorCloudProvider[] = [
    {
      id: 'openai',
      name: 'OpenAI',
      description: 'Create manuscript embeddings with OpenAI models.',
      keyPlaceholder: 'sk-...',
    },
    {
      id: 'voyage',
      name: 'Voyage AI',
      description: 'Create manuscript embeddings with Voyage models.',
      keyPlaceholder: 'Enter your Voyage AI API key',
    },
  ];
  readonly localModelTiers: readonly { id: LocalEmbeddingModelTier; label: string }[] = [
    { id: 'large', label: 'Large' },
    { id: 'medium', label: 'Medium' },
    { id: 'small', label: 'Small' },
  ];

  readonly selectedProviderId = signal<VectorCloudProviderId | null>(null);
  readonly apiKeyVisible = signal(false);
  readonly apiKeyDrafts = signal<Record<VectorCloudProviderId, string>>({
    openai: '',
    voyage: '',
  });
  readonly localModelStatuses = this.localModelState.statuses;
  readonly selectedLocalModelTier = this.localModelState.selectedTier;
  readonly localModelStatusLoading = this.localModelState.statusLoading;
  readonly localModelOperation = this.localModelState.operation;
  readonly localModelProgress = this.localModelState.progress;
  readonly localModelErrors = this.localModelState.errors;
  readonly localModelLoadError = this.localModelState.loadError;

  readonly selectedProvider = computed(() => {
    const providerId = this.selectedProviderId();
    return this.providers.find((provider) => provider.id === providerId) ?? null;
  });

  ngOnInit(): void {
    void this.localModelState.ensureStatuses().catch(() => undefined);
  }

  async loadLocalModelStatus(): Promise<void> {
    await this.localModelState.reloadStatuses().catch(() => undefined);
  }

  async downloadLocalModel(modelName: LocalEmbeddingModelName): Promise<void> {
    await this.localModelState.download(modelName);
  }

  requestLocalModelUninstall(status: LocalEmbeddingModelStatus): void {
    if (this.localModelOperation()) return;

    const action = status.installed ? 'Uninstall' : 'Remove downloaded files for';
    this.confirmService.open(
      `${action} local model?`,
      `${status.modelName} will be removed from this device. You can download it again later.`,
      (clearVectors) => {
        void this.uninstallLocalModel(status.modelName, clearVectors);
      },
      undefined,
      {
        confirmLabel: status.installed ? 'Uninstall' : 'Remove files',
        checkboxLabel: 'Also delete vectors generated by this model.',
      },
    );
  }

  formatBytes(bytes: number): string {
    if (bytes === 0) return '0 B';

    const units = ['B', 'KB', 'MB', 'GB', 'TB'];
    const unitIndex = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
    const value = bytes / 1024 ** unitIndex;
    return `${new Intl.NumberFormat('en-US', { maximumFractionDigits: 1 }).format(value)} ${units[unitIndex]}`;
  }

  downloadPercentage(modelName: LocalEmbeddingModelName): number | null {
    const progress = this.localModelProgress();
    if (!progress || progress.modelName !== modelName) return null;
    if (typeof progress.progress === 'number') return this.clampPercentage(progress.progress);
    if (
      typeof progress.loaded === 'number' &&
      typeof progress.total === 'number' &&
      progress.total > 0
    ) {
      return this.clampPercentage((progress.loaded / progress.total) * 100);
    }
    return null;
  }

  modelsForTier(tier: LocalEmbeddingModelTier): LocalEmbeddingModelStatus[] {
    return this.localModelStatuses().filter((status) => status.tier === tier);
  }

  selectLocalModelTier(tier: LocalEmbeddingModelTier): void {
    this.localModelState.selectTier(tier);
  }

  modelError(modelName: LocalEmbeddingModelName): string | null {
    return this.localModelErrors()[modelName] ?? null;
  }

  isModelOperation(modelName: LocalEmbeddingModelName, type?: LocalModelOperationType): boolean {
    const operation = this.localModelOperation();
    return operation?.modelName === modelName && (!type || operation.type === type);
  }

  private async uninstallLocalModel(
    modelName: LocalEmbeddingModelName,
    clearVectors: boolean,
  ): Promise<void> {
    await this.localModelState.uninstall(modelName, clearVectors);
  }

  private clampPercentage(value: number): number {
    return Math.round(Math.min(100, Math.max(0, value)));
  }

  selectProvider(providerId: VectorCloudProviderId): void {
    this.selectedProviderId.set(providerId);
    this.apiKeyVisible.set(false);
  }

  updateApiKey(providerId: VectorCloudProviderId, event: Event): void {
    const value = (event.target as HTMLInputElement).value;
    this.apiKeyDrafts.update((drafts) => ({ ...drafts, [providerId]: value }));
  }

  toggleApiKeyVisibility(): void {
    this.apiKeyVisible.update((visible) => !visible);
  }

  apiKeyInputType(): 'text' | 'password' {
    return this.apiKeyVisible() ? 'text' : 'password';
  }

  /** Persistence will be connected when the vector configuration backend is implemented. */
  saveApiKeyOnBlur(_providerId: VectorCloudProviderId): void {}

  /** Connection testing will be connected when the vector configuration backend is implemented. */
  testConnection(_providerId: VectorCloudProviderId): void {}
}
